### PR TITLE
Adding error handling for when the JSPM bundle fails.

### PR DESCRIPTION
**Pull request by ashleynolan**
Adds error handling for when the JSPM bundle fails – such as when a syntax error occurs in the JS to be bundled.

This can then be used with the `gulp-plumber` plugin to prevent watch tasks from breaking when these errors occur – this will instead handle the error and allow the stream to continue running.

### CODE REVIEW

**Comment by ashleynolan** [comment]
Any chance of getting this PR reviewed?

Without it, I have to restart my gulp task every time an error occurs when producing self executing bundles.

**Comment by brillout** [comment]
Yes, I'll review it today

**Comment by ashleynolan** [comment]
Great - thanks!

**Comment by brillout** [comment]
I'm not a Promise expert, but wouldn't
```
scope.emit('error', new gutil.PluginError(projectName, 'JSPM Bundle failing: \n' + error ));
throw new Error(error);
```
do the trick?

**Comment by brillout** [comment]
thanks for the PR btw!

**Comment by ashleynolan** [comment]
I tried that at first, but it just returns unhandled rejection errors – I think this happens because it’s a nested Promise, and so it doesn’t bubble up – you’d effectively have to have an error handler for each `.then()` in the chain to handle this, which seemed a bit overkill.

After reading the Bluebird docs, seemed like using their promise cancellation was the best way to go.

**Comment by brillout** [comment]
I believe that just one catch would work. Ideally the catch would be defined on the Promise of `throw new Error(err)`

**Comment by brillout** [comment]
Are you sure the rejection doesn't bubble up?
In the following code snippet the rejection is bubbled up and the catch is called, as one would expect
```
Promise.resolve().then(() => Promise.resolve().then(() => {throw 'er'})).then(() => console.log('pass')).catch(() => console.log('catch'))
```

**Pull request closed without merging**
