### PR TITLE
nested paths like `gulp.src('www/js/main.js')` get truncated

### PR DESCRIPTION
**Pull request by tniswong**
Introduced by #12 

Basically `www/js/main.js` is converted to `main.js`, which causes SystemJS to look in the wrong directory and causes the build to fail.

My fix crafts a path relative to the node working directory. I also tested this on Windows, so #8 should still be fine.

### CODE REVIEW

**Comment by brillout** [comment]
This makes `npm test` fail.
I'll have a closer look at it later.
Thanks for opening the PR.

**Comment by tniswong** [comment]
Looked at fixing the tests... seems nontrivial. Combination of setting appropriate location for the demo package.json and assuring new calculated relative path is relative to the appropriate place. Still looking at this, but no promises.

**Comment by decherneyge** [comment]
When the file is getting truncated, do you have the directories properties setup in your package.json ?

**Comment by tniswong** [comment]
@decherneyge No.

**Comment by tniswong** [comment]
FYI - Working on a fix to these tests. However, there are some issues with the unit tests being intertwined with the demo code. I'm working on separating these entirely, renaming `demo/` to `example/`, making `example/` entirely standalone, and duplicating the code in an isolated manner for use specifically within the unit tests.

**Comment by brillout** [comment]
Your PR makes the path relative to the current working directory.
The current working directory can be anything.
Therefore and depending on what the current working directory is, the path won't be relative to the JSPM base directory.

It would be convenient to use the absolute path again like it was before #12 https://github.com/brillout/gulp-jspm/blob/18a6cfe51b44dd4a39e69039396466aa6078c241/index.js#L44

But I'm not sure how to make absolute paths work with the JSPM API.
Any ideas @tniswong , @decherneyge ?

**Comment by tniswong** [comment]
Yeah, I think I got it working, actually. What I had to do in the end was hook into Liftoff. This way, I could change my relativeUrl calculation from the project root to be related to the `configBase`. Once I had the `configBase`, I could get access to the jspm `directories` property of `package.json`. Once I had both of those, I could `path.join` them. And, obviously, I'd skip the path.join if the `directories` property wasn't available.

Commit Incoming, though be warned, I've not tested it on Windows yet.

**Comment by tniswong** [comment]
Also, ignore my previous comment related to separating out the `demo/` code from the unit tests. Turned out it was easier than that.

**Comment by tniswong** [comment]
Ok @decherneyge and @brillout, give this one a shot.

**Comment by brillout** [comment]
Nice, thank you.

And how about `var jspm_input = path.relative(jspmRoot, file.path);` instead of `var jspm_input = path.relative(path.resolve(jspmRoot || ''), file.path);`?

**Comment by tniswong** [comment]
Seems reasonable. I guess I was just covering for `env.configBase` since I don't actually know how it works.

**Pull request merged**
