### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by decherneyge**
fix windows issue with pathing 
issue #8

### CODE REVIEW

**Comment by brillout** [comment]
thanks

**Comment by decherneyge** [comment]
Thank you for making and maintaining gulp-jspm. Any idea of when you will next publish to npm?

**Comment by brillout** [comment]
once we fix https://github.com/brillout/gulp-jspm/pull/13
thanks for the PR!

**Comment by brillout** [comment]
a new version is now on npm

**Pull request merged**
