### PR TITLE
Adding additional bundle options to option list

### PR DESCRIPTION
**Pull request by ashleynolan**
Updating bundle options to allow for minify, mangle and lowResSourceMaps, inline with the JSPM bundle API optionsaps, inline with the JSPM bundle API options

### CODE REVIEW

**Comment by dlebedynskyi** [comment]
Upvote for this pull

**Comment by brillout** [comment]
I'm not sure why you want these lines to be added? Doesn't jspm behave the same either `miniy` is set to `false` or to `undefined`?

**Comment by ashleynolan** [comment]
No, if you set minify to `true`, it minifies the bundle.  The other included lines are all options for the bundle config as well.

**Comment by brillout** [comment]
Yes `jspm` behaves differently if `minify` is set to `true` or to `false`. But does it between `undefined` and `false`? Your code solely sets falsy options to `false`.

Note that all options passed to `gulp-jspm` are passed on to `jspm`.

What do you want to achieve?

**Comment by ashleynolan** [comment]
The code I've added lets you define the options as true, and if they're not present in the options it will set them to false.

I have tested this code locally (setting minify option to true) and it works as expected, passing the true value to JSPM. If it's undefined, it will default to false, as it does now.

**Comment by brillout** [comment]
You say "The code I've added lets you define the options as true" but this is already the case. Your PR doesn't make any difference to the behavior of `gulp-jspm`. See this line in the code; https://github.com/brillout/gulp-jspm/blob/master/index.js#L59 or the readme mention `all other options given to gulp-jspm are passed on to jspm`.

**Comment by ashleynolan** [comment]
Ah, ok – I didn’t realise it passed through other values on to JSPM.

Closing this PR.

**Comment by brillout** [comment]
I've just updated the Readme to make it more clear that all jspm options are supported. Thanks for the PR!

**Pull request closed without merging**
