### PR TITLE
Allow creating of self executing bundles.

### PR DESCRIPTION
**Pull request by yelvert**

### CODE REVIEW

**Comment by jigfox** [comment]
looks good, I want to use this feature, any

**Comment by brillout** [comment]
I'm going to look at it today

**Comment by jigfox** [comment]
Thanks @brillout 👍

**Comment by brillout** [comment]
@yelvert thanks!
@jigfox `npm install gulp-jspm@0.3.2`

**Comment by jigfox** [comment]
@brillout thanks for merging
@yelvert thanks for creating the merge request, I was just about creating one, when I saw yours

**Pull request merged**
